spring:
  application:
    name: Zuul-gateway

server:
 port: 9000
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
zuul:
  sensitive-headers: Cookie,Set-Cookie
  routes:
    mainrequest:
      service-id: MAINREQUESTSERVICE
    accomodationrequest:
      service-id: ACCOMODATIONSERVICE
  host:
    socket-timeout-millis: 90000      
     